---
title: "Search a Table for a Value"
output:
  html_document:
    df_print: paged
  html_notebook:
    df_print: paged
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  cache = TRUE,
  message = FALSE
)
```

# Search for an Exact String Match  

```{r setup}
library(pg13)
conn <- localConnect(dbname = "athena",
                     port = 5432)
```

```{r}
searchTable(conn = conn,
            schema = "omop_vocabulary",
            tableName = "concept",
            values = "Aspirin",
            case_insensitive = TRUE)

```

```{r}
searchTable(conn = conn,
            schema = "omop_vocabulary",
            tableName = "concept",
            values = "Aspirin",
            case_insensitive = FALSE)
```

```{r}
searchTable(conn = conn,
            schema = "omop_vocabulary",
            tableName = "concept",
            values = "Aspirin",
            case_insensitive = FALSE,
            verbose = FALSE)
```

```{r}
searchTable(conn = conn,
            schema = "omop_vocabulary",
            tableName = "concept",
            values = "Aspirin",
            case_insensitive = FALSE,
            verbose = FALSE,
            render_sql = TRUE,
            "concept_id",
            "concept_name")

```

```{r}
searchTable(conn = conn,
            schema = "omop_vocabulary",
            tableName = "concept",
            c("concept_id", "concept_name"),
            values = "Aspirin",
            case_insensitive = FALSE,
            verbose = FALSE,
            render_sql = TRUE)
```

```{r}
dc(conn = conn,
   remove = TRUE)
```

